### ISSUE TITLE
What about using libyui? TUI+GUI support in one!

### ISSUE THREAD

**Issue by timofonic** [cglindkamp/dfm#1]
Hello.

Thanks for your project, it seems quite interesting.

I use console most of the time, but sometimes I prefer the GUI approach. I often use remote shells and in those cases, I use console apps and many of them use ncurses/s-lang or whatever (as you may know, some programs use minimal parts of ncurses, but that's another topic).

What about using [libyui](https://github.com/libyui/)? This way, your program will be available for TUI (ncurses) and GUI (Gtk, Qt). it would make your program a lot more flexible and adapt better to different Desktop Environments. Originally it was developed for OpenSUSE's YaST, but it can be used by any project ;)

Kind regards.

**Comment by cglindkamp** [comment]
I previously started to develop a similar project with Qt, but I felt like I'm constantly fighting the Qt event system and standard widget behaviour (overriding all standard key events to get similar behaviour like in dfm now). I think it wouldn't be much different with libyui, but I didn't have a look at it for a while. Thats why I went the text-only route.

Nevertheless, even if libyui would work for dfm, switching to it would be a substantial amount of work, mostly because it is a C++ library and dfm is written in C. It would basically be a rewrite. So I think this is out of the question for the time being.
